### ISSUE TITLE
Make the addition of the cron jobs configurable

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape-chef#32]
At present, fallback machines like cyclescape5 shouldn't be set to process mail (and maybe planning applications).

This means that a chef rollout must at present be followed by a manual step of commenting-out the cron job(s).

So it would be good to make this configurable on a per-host basis.

**Comment by gravitystorm** [comment]
The best approach is to make the cron jobs depend on a per-node attribute. So in the cookbook have an attributes file with something like `default['cyclescape']['mail']['processing'] = false` and then override this with an attribute on the node you want to actually run the mail processing.

**Comment by mvl22** [comment]
Although there is a hotfix in https://github.com/cyclestreets/cyclescape-chef/commit/2c5376e8d2bea0 this isn't really a long-term solution, as it's hard-coded to a specific host (which will no doubt change as time goes on) and not relevant to third-party use.

So in due course it would be good to make this a setting or do this in the way that a central-server -based Chef would normally handle this.

**Comment by nikolai-b** [comment]
I think we should have a `staging.json` and a `production.json` (instead of just the `node.json`), and change the `RAILS_ENV` accordingly.  The SSL certs aren't valid in staging so we could add a bit of logic to only use http (obviously that would mean not using real passwords etc.)  Not high priority but would help with login / group checking issues which I don't think can be checked currently.

**Comment by nikolai-b** [comment]
I have done this so 
`chef-solo -c solo.rb -j staging.json` runs the deploy with staging env and 
`chef-solo -c solo.rb -j node.json` runs the production deploy.
