### ISSUE TITLE
Mail delayed in week ending 20th August 2016

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape-chef#36]
A user has noted that a pile of e-mail clearly intended for earlier in the week was delayed until 20th August 2016.

See: `/threads/227#message_35369`.

This isn't necessarily a problem with the chef repo per sé, but does need to be checked out as a deployment issue.

**Comment by nikolai-b** [comment]
The cron emails you flagged up were a symptom of this. 
```
/bin/bash -l -c 'cd /var/www/cyclescape/releases/588287e8955e502ab5f94c5600c2a85c52149527 && bundle exec rails runner -e production '\''MailboxReader.process_all_mailboxes'\
```
was saying that the emails were not being processed.  This was due to a change in `whenever`

https://github.com/javan/whenever/blob/master/CHANGELOG.md#095--june-12-2016

> Execute runner with bundle exec to ensure presence of app dependencies [Judith Roth]

We should really migrate all of these to rake tasks as that is more robust, rake being a stand alone and then that can call the rails method.
